# Project-wide Gradle settings

# Specifies the JVM arguments used for the daemon process
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX package structure
android.useAndroidX=true
android.enableJetifier=true

# Kotlin code style
kotlin.code.style=official

# Enable configuration cache
org.gradle.configuration-cache=true
